//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("PololuMaestro")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("PololuMaestro")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="PololuMaestro.Y2012.M04, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d6f1900" +
    "a66fa3281")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformPololuMaestro {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::PololuMaestro.Proxy.PololuMaestroState), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_Proxy_PololuMaestroState_TO_PololuMaestro_PololuMaestroState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::PololuMaestro.PololuMaestroState), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_PololuMaestroState_TO_PololuMaestro_Proxy_PololuMaestroState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::PololuMaestro.Proxy.ChannelInfo), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_Proxy_ChannelInfo_TO_PololuMaestro_ChannelInfo));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::PololuMaestro.ChannelInfo), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_ChannelInfo_TO_PololuMaestro_Proxy_ChannelInfo));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::PololuMaestro.Proxy.ChannelSetting), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_Proxy_ChannelSetting_TO_PololuMaestro_ChannelSetting));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::PololuMaestro.ChannelSetting), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_ChannelSetting_TO_PololuMaestro_Proxy_ChannelSetting));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::PololuMaestro.Proxy.ChannelPose), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_Proxy_ChannelPose_TO_PololuMaestro_ChannelPose));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::PololuMaestro.ChannelPose), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_ChannelPose_TO_PololuMaestro_Proxy_ChannelPose));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::PololuMaestro.Proxy.GetDeviceListResponseType), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_Proxy_GetDeviceListResponseType_TO_PololuMaestro_GetDeviceListResponseType));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::PololuMaestro.GetDeviceListResponseType), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_GetDeviceListResponseType_TO_PololuMaestro_Proxy_GetDeviceListResponseType));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::PololuMaestro.Proxy.DeviceListItem), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_Proxy_DeviceListItem_TO_PololuMaestro_DeviceListItem));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::PololuMaestro.DeviceListItem), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_DeviceListItem_TO_PololuMaestro_Proxy_DeviceListItem));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::PololuMaestro.Proxy.SetServoRequestType), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_Proxy_SetServoRequestType_TO_PololuMaestro_SetServoRequestType));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::PololuMaestro.SetServoRequestType), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_SetServoRequestType_TO_PololuMaestro_Proxy_SetServoRequestType));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::PololuMaestro.Proxy.ServoChangeRequestType), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_Proxy_ServoChangeRequestType_TO_PololuMaestro_ServoChangeRequestType));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::PololuMaestro.ServoChangeRequestType), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_ServoChangeRequestType_TO_PololuMaestro_Proxy_ServoChangeRequestType));
        }
        
        public static object PololuMaestro_Proxy_PololuMaestroState_TO_PololuMaestro_PololuMaestroState(object transformFrom) {
            global::PololuMaestro.PololuMaestroState target = new global::PololuMaestro.PololuMaestroState();
            global::PololuMaestro.Proxy.PololuMaestroState from = ((global::PololuMaestro.Proxy.PololuMaestroState)(transformFrom));
            if ((from.Channels != null)) {
                int count = from.Channels.Count;
                global::System.Collections.Generic.List<global::PololuMaestro.ChannelInfo> tmp = new global::System.Collections.Generic.List<global::PololuMaestro.ChannelInfo>(count);
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::PololuMaestro.ChannelInfo tmp0 = default(global::PololuMaestro.ChannelInfo);
                    if ((from.Channels[index] != null)) {
                        tmp0 = ((global::PololuMaestro.ChannelInfo)(PololuMaestro_Proxy_ChannelInfo_TO_PololuMaestro_ChannelInfo(from.Channels[index])));
                    }
                    else {
                        tmp0 = null;
                    }
                    tmp.Add(tmp0);
                }
                target.Channels = tmp;
            }
            else {
                target.Channels = null;
            }
            target.SerialNumber = from.SerialNumber;
            target.Connected = from.Connected;
            target.PollingInterval = from.PollingInterval;
            return target;
        }
        
        public static object PololuMaestro_PololuMaestroState_TO_PololuMaestro_Proxy_PololuMaestroState(object transformFrom) {
            global::PololuMaestro.Proxy.PololuMaestroState target = new global::PololuMaestro.Proxy.PololuMaestroState();
            global::PololuMaestro.PololuMaestroState from = ((global::PololuMaestro.PololuMaestroState)(transformFrom));
            global::System.Collections.Generic.List<global::PololuMaestro.ChannelInfo> tmp = from.Channels;
            if ((tmp != null)) {
                int count = tmp.Count;
                global::System.Collections.Generic.List<global::PololuMaestro.Proxy.ChannelInfo> tmp0 = new global::System.Collections.Generic.List<global::PololuMaestro.Proxy.ChannelInfo>(count);
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::PololuMaestro.Proxy.ChannelInfo tmp1 = default(global::PololuMaestro.Proxy.ChannelInfo);
                    global::PololuMaestro.ChannelInfo tmp2 = tmp[index];
                    if ((tmp2 != null)) {
                        tmp1 = ((global::PololuMaestro.Proxy.ChannelInfo)(PololuMaestro_ChannelInfo_TO_PololuMaestro_Proxy_ChannelInfo(tmp2)));
                    }
                    tmp0.Add(tmp1);
                }
                target.Channels = tmp0;
            }
            target.SerialNumber = from.SerialNumber;
            target.Connected = from.Connected;
            target.PollingInterval = from.PollingInterval;
            return target;
        }
        
        public static object PololuMaestro_Proxy_ChannelInfo_TO_PololuMaestro_ChannelInfo(object transformFrom) {
            global::PololuMaestro.ChannelInfo target = new global::PololuMaestro.ChannelInfo();
            global::PololuMaestro.Proxy.ChannelInfo from = ((global::PololuMaestro.Proxy.ChannelInfo)(transformFrom));
            target.Index = from.Index;
            if ((from.Setting != null)) {
                target.Setting = ((global::PololuMaestro.ChannelSetting)(PololuMaestro_Proxy_ChannelSetting_TO_PololuMaestro_ChannelSetting(from.Setting)));
            }
            else {
                target.Setting = null;
            }
            if ((from.Pose != null)) {
                target.Pose = ((global::PololuMaestro.ChannelPose)(PololuMaestro_Proxy_ChannelPose_TO_PololuMaestro_ChannelPose(from.Pose)));
            }
            else {
                target.Pose = null;
            }
            return target;
        }
        
        public static object PololuMaestro_ChannelInfo_TO_PololuMaestro_Proxy_ChannelInfo(object transformFrom) {
            global::PololuMaestro.Proxy.ChannelInfo target = new global::PololuMaestro.Proxy.ChannelInfo();
            global::PololuMaestro.ChannelInfo from = ((global::PololuMaestro.ChannelInfo)(transformFrom));
            target.Index = from.Index;
            global::PololuMaestro.ChannelSetting tmp = from.Setting;
            if ((tmp != null)) {
                target.Setting = ((global::PololuMaestro.Proxy.ChannelSetting)(PololuMaestro_ChannelSetting_TO_PololuMaestro_Proxy_ChannelSetting(tmp)));
            }
            global::PololuMaestro.ChannelPose tmp0 = from.Pose;
            if ((tmp0 != null)) {
                target.Pose = ((global::PololuMaestro.Proxy.ChannelPose)(PololuMaestro_ChannelPose_TO_PololuMaestro_Proxy_ChannelPose(tmp0)));
            }
            return target;
        }
        
        public static object PololuMaestro_Proxy_ChannelSetting_TO_PololuMaestro_ChannelSetting(object transformFrom) {
            global::PololuMaestro.ChannelSetting target = new global::PololuMaestro.ChannelSetting();
            global::PololuMaestro.Proxy.ChannelSetting from = ((global::PololuMaestro.Proxy.ChannelSetting)(transformFrom));
            target.Name = from.Name;
            target.Mode = ((global::PololuMaestro.ChannelMode)(((int)(from.Mode))));
            target.HomeMode = ((global::PololuMaestro.HomeMode)(((int)(from.HomeMode))));
            target.HomePosition = from.HomePosition;
            target.MinimumPosition = from.MinimumPosition;
            target.MaximumPosition = from.MaximumPosition;
            target.NeutralPosition = from.NeutralPosition;
            target.Range = from.Range;
            target.MaximumSpeed = from.MaximumSpeed;
            target.MaximumAcceleration = from.MaximumAcceleration;
            target.Timestamp = from.Timestamp;
            return target;
        }
        
        public static object PololuMaestro_ChannelSetting_TO_PololuMaestro_Proxy_ChannelSetting(object transformFrom) {
            global::PololuMaestro.Proxy.ChannelSetting target = new global::PololuMaestro.Proxy.ChannelSetting();
            global::PololuMaestro.ChannelSetting from = ((global::PololuMaestro.ChannelSetting)(transformFrom));
            target.Name = from.Name;
            target.Mode = ((global::PololuMaestro.Proxy.ChannelMode)(((int)(from.Mode))));
            target.HomeMode = ((global::PololuMaestro.Proxy.HomeMode)(((int)(from.HomeMode))));
            target.HomePosition = from.HomePosition;
            target.MinimumPosition = from.MinimumPosition;
            target.MaximumPosition = from.MaximumPosition;
            target.NeutralPosition = from.NeutralPosition;
            target.Range = from.Range;
            target.MaximumSpeed = from.MaximumSpeed;
            target.MaximumAcceleration = from.MaximumAcceleration;
            target.Timestamp = from.Timestamp;
            return target;
        }
        
        public static object PololuMaestro_Proxy_ChannelPose_TO_PololuMaestro_ChannelPose(object transformFrom) {
            global::PololuMaestro.ChannelPose target = new global::PololuMaestro.ChannelPose();
            global::PololuMaestro.Proxy.ChannelPose from = ((global::PololuMaestro.Proxy.ChannelPose)(transformFrom));
            target.Target = from.Target;
            target.Position = from.Position;
            target.Acceleration = from.Acceleration;
            target.Speed = from.Speed;
            target.Timestamp = from.Timestamp;
            return target;
        }
        
        public static object PololuMaestro_ChannelPose_TO_PololuMaestro_Proxy_ChannelPose(object transformFrom) {
            global::PololuMaestro.Proxy.ChannelPose target = new global::PololuMaestro.Proxy.ChannelPose();
            global::PololuMaestro.ChannelPose from = ((global::PololuMaestro.ChannelPose)(transformFrom));
            target.Target = from.Target;
            target.Position = from.Position;
            target.Acceleration = from.Acceleration;
            target.Speed = from.Speed;
            target.Timestamp = from.Timestamp;
            return target;
        }
        
        public static object PololuMaestro_Proxy_GetDeviceListResponseType_TO_PololuMaestro_GetDeviceListResponseType(object transformFrom) {
            global::PololuMaestro.GetDeviceListResponseType target = new global::PololuMaestro.GetDeviceListResponseType();
            global::PololuMaestro.Proxy.GetDeviceListResponseType from = ((global::PololuMaestro.Proxy.GetDeviceListResponseType)(transformFrom));
            if ((from.Devices != null)) {
                int count = from.Devices.Length;
                global::PololuMaestro.DeviceListItem[] tmp = new global::PololuMaestro.DeviceListItem[count];
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::PololuMaestro.DeviceListItem tmp0 = default(global::PololuMaestro.DeviceListItem);
                    if ((from.Devices[index] != null)) {
                        tmp0 = ((global::PololuMaestro.DeviceListItem)(PololuMaestro_Proxy_DeviceListItem_TO_PololuMaestro_DeviceListItem(from.Devices[index])));
                    }
                    else {
                        tmp0 = null;
                    }
                    tmp[index] = tmp0;
                }
                target.Devices = tmp;
            }
            else {
                target.Devices = null;
            }
            return target;
        }
        
        public static object PololuMaestro_GetDeviceListResponseType_TO_PololuMaestro_Proxy_GetDeviceListResponseType(object transformFrom) {
            global::PololuMaestro.Proxy.GetDeviceListResponseType target = new global::PololuMaestro.Proxy.GetDeviceListResponseType();
            global::PololuMaestro.GetDeviceListResponseType from = ((global::PololuMaestro.GetDeviceListResponseType)(transformFrom));
            PololuMaestro.DeviceListItem[] tmp = from.Devices;
            if ((tmp != null)) {
                int count = tmp.Length;
                global::PololuMaestro.Proxy.DeviceListItem[] tmp0 = new global::PololuMaestro.Proxy.DeviceListItem[count];
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::PololuMaestro.Proxy.DeviceListItem tmp1 = default(global::PololuMaestro.Proxy.DeviceListItem);
                    global::PololuMaestro.DeviceListItem tmp2 = tmp[index];
                    if ((tmp2 != null)) {
                        tmp1 = ((global::PololuMaestro.Proxy.DeviceListItem)(PololuMaestro_DeviceListItem_TO_PololuMaestro_Proxy_DeviceListItem(tmp2)));
                    }
                    tmp0[index] = tmp1;
                }
                target.Devices = tmp0;
            }
            return target;
        }
        
        public static object PololuMaestro_Proxy_DeviceListItem_TO_PololuMaestro_DeviceListItem(object transformFrom) {
            global::PololuMaestro.DeviceListItem target = new global::PololuMaestro.DeviceListItem();
            global::PololuMaestro.Proxy.DeviceListItem from = ((global::PololuMaestro.Proxy.DeviceListItem)(transformFrom));
            target.SerialNumber = from.SerialNumber;
            target.DisplayName = from.DisplayName;
            target.ProductId = from.ProductId;
            target.Guid = from.Guid;
            return target;
        }
        
        public static object PololuMaestro_DeviceListItem_TO_PololuMaestro_Proxy_DeviceListItem(object transformFrom) {
            global::PololuMaestro.Proxy.DeviceListItem target = new global::PololuMaestro.Proxy.DeviceListItem();
            global::PololuMaestro.DeviceListItem from = ((global::PololuMaestro.DeviceListItem)(transformFrom));
            target.SerialNumber = from.SerialNumber;
            target.DisplayName = from.DisplayName;
            target.ProductId = from.ProductId;
            target.Guid = from.Guid;
            return target;
        }
        
        public static object PololuMaestro_Proxy_SetServoRequestType_TO_PololuMaestro_SetServoRequestType(object transformFrom) {
            global::PololuMaestro.SetServoRequestType target = new global::PololuMaestro.SetServoRequestType();
            global::PololuMaestro.Proxy.SetServoRequestType from = ((global::PololuMaestro.Proxy.SetServoRequestType)(transformFrom));
            target.ServoIndex = from.ServoIndex;
            target.Target = from.Target;
            target.Acceleration = from.Acceleration;
            target.Speed = from.Speed;
            return target;
        }
        
        public static object PololuMaestro_SetServoRequestType_TO_PololuMaestro_Proxy_SetServoRequestType(object transformFrom) {
            global::PololuMaestro.Proxy.SetServoRequestType target = new global::PololuMaestro.Proxy.SetServoRequestType();
            global::PololuMaestro.SetServoRequestType from = ((global::PololuMaestro.SetServoRequestType)(transformFrom));
            target.ServoIndex = from.ServoIndex;
            target.Target = from.Target;
            target.Acceleration = from.Acceleration;
            target.Speed = from.Speed;
            return target;
        }
        
        public static object PololuMaestro_Proxy_ServoChangeRequestType_TO_PololuMaestro_ServoChangeRequestType(object transformFrom) {
            global::PololuMaestro.ServoChangeRequestType target = new global::PololuMaestro.ServoChangeRequestType();
            global::PololuMaestro.Proxy.ServoChangeRequestType from = ((global::PololuMaestro.Proxy.ServoChangeRequestType)(transformFrom));
            target.Index = from.Index;
            if ((from.CurrentPose != null)) {
                target.CurrentPose = ((global::PololuMaestro.ChannelPose)(PololuMaestro_Proxy_ChannelPose_TO_PololuMaestro_ChannelPose(from.CurrentPose)));
            }
            else {
                target.CurrentPose = null;
            }
            return target;
        }
        
        public static object PololuMaestro_ServoChangeRequestType_TO_PololuMaestro_Proxy_ServoChangeRequestType(object transformFrom) {
            global::PololuMaestro.Proxy.ServoChangeRequestType target = new global::PololuMaestro.Proxy.ServoChangeRequestType();
            global::PololuMaestro.ServoChangeRequestType from = ((global::PololuMaestro.ServoChangeRequestType)(transformFrom));
            target.Index = from.Index;
            global::PololuMaestro.ChannelPose tmp = from.CurrentPose;
            if ((tmp != null)) {
                target.CurrentPose = ((global::PololuMaestro.Proxy.ChannelPose)(PololuMaestro_ChannelPose_TO_PololuMaestro_Proxy_ChannelPose(tmp)));
            }
            return target;
        }
    }
}
