//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("PololuMaestro")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("PololuMaestro")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Proxy, SourceAssemblyKey="PololuMaestro.Y2012.M04, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d6f1900" +
    "a66fa3281")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace PololuMaestro.Proxy {
    
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html", ElementName="PololuMaestroState")]
    public class PololuMaestroState : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public PololuMaestroState() {
        }
        
        private global::System.Collections.Generic.List<global::PololuMaestro.Proxy.ChannelInfo> _Channels;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.Collections.Generic.List<global::PololuMaestro.Proxy.ChannelInfo> Channels {
            get {
                return this._Channels;
            }
            set {
                this._Channels = value;
            }
        }
        
        private string _SerialNumber;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Serial number of selected device.")]
        public string SerialNumber {
            get {
                return this._SerialNumber;
            }
            set {
                this._SerialNumber = value;
            }
        }
        
        private bool _Connected;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public bool Connected {
            get {
                return this._Connected;
            }
            set {
                this._Connected = value;
            }
        }
        
        private int _PollingInterval;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public int PollingInterval {
            get {
                return this._PollingInterval;
            }
            set {
                this._PollingInterval = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current PololuMaestroState to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::PololuMaestro.Proxy.PololuMaestroState typedTarget = ((global::PololuMaestro.Proxy.PololuMaestroState)(target));
            if ((this._Channels != null)) {
                int count = this._Channels.Count;
                global::System.Collections.Generic.List<global::PololuMaestro.Proxy.ChannelInfo> tmp = new global::System.Collections.Generic.List<global::PololuMaestro.Proxy.ChannelInfo>(count);
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::PololuMaestro.Proxy.ChannelInfo tmp0 = default(global::PololuMaestro.Proxy.ChannelInfo);
                    if ((this._Channels[index] != null)) {
                        global::PololuMaestro.Proxy.ChannelInfo tmp1 = new global::PololuMaestro.Proxy.ChannelInfo();
                        ((Microsoft.Dss.Core.IDssSerializable)(this._Channels[index])).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp1)));
                        tmp0 = tmp1;
                    }
                    tmp.Add(tmp0);
                }
                typedTarget._Channels = tmp;
            }
            typedTarget._SerialNumber = this._SerialNumber;
            typedTarget._Connected = this._Connected;
            typedTarget._PollingInterval = this._PollingInterval;
        }
        
        /// <summary>
        ///Clones PololuMaestroState
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::PololuMaestro.Proxy.PololuMaestroState target0 = new global::PololuMaestro.Proxy.PololuMaestroState();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current PololuMaestroState to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            if ((this._Channels == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._Channels.Count);
                for (int indexChannels = 0; (indexChannels < this._Channels.Count); indexChannels = (indexChannels + 1)) {
                    if ((this._Channels[indexChannels] == null)) {
                        writer.Write(((byte)(0)));
                    }
                    else {
                        writer.Write(((byte)(1)));
                        ((Microsoft.Dss.Core.IDssSerializable)(this._Channels[indexChannels])).Serialize(writer);
                    }
                }
            }
            if ((this._SerialNumber == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._SerialNumber);
            }
            writer.Write(this._Connected);
            writer.Write(this._PollingInterval);
        }
        
        /// <summary>
        ///Deserializes PololuMaestroState
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized PololuMaestroState</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            if ((reader.ReadByte() != 0)) {
                int count0 = reader.ReadInt32();
                this._Channels = new global::System.Collections.Generic.List<global::PololuMaestro.Proxy.ChannelInfo>(count0);
                for (int index0 = 0; (index0 < count0); index0 = (index0 + 1)) {
                    this._Channels.Add(default(global::PololuMaestro.Proxy.ChannelInfo));
                    if ((reader.ReadByte() != 0)) {
                        this._Channels[index0] = ((global::PololuMaestro.Proxy.ChannelInfo)(((Microsoft.Dss.Core.IDssSerializable)(new global::PololuMaestro.Proxy.ChannelInfo())).Deserialize(reader)));
                    }
                }
            }
            if ((reader.ReadByte() != 0)) {
                this._SerialNumber = reader.ReadString();
            }
            this._Connected = reader.ReadBoolean();
            this._PollingInterval = reader.ReadInt32();
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html", ElementName="ChannelInfo")]
    [global::System.ComponentModel.DescriptionAttribute("The state of a servo.")]
    public class ChannelInfo : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public ChannelInfo() {
        }
        
        private int _Index;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public int Index {
            get {
                return this._Index;
            }
            set {
                this._Index = value;
            }
        }
        
        private global::PololuMaestro.Proxy.ChannelSetting _Setting;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::PololuMaestro.Proxy.ChannelSetting Setting {
            get {
                return this._Setting;
            }
            set {
                this._Setting = value;
            }
        }
        
        private global::PololuMaestro.Proxy.ChannelPose _Pose;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::PololuMaestro.Proxy.ChannelPose Pose {
            get {
                return this._Pose;
            }
            set {
                this._Pose = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current ChannelInfo to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::PololuMaestro.Proxy.ChannelInfo typedTarget = ((global::PololuMaestro.Proxy.ChannelInfo)(target));
            typedTarget._Index = this._Index;
            if ((this._Setting != null)) {
                global::PololuMaestro.Proxy.ChannelSetting tmp = new global::PololuMaestro.Proxy.ChannelSetting();
                ((Microsoft.Dss.Core.IDssSerializable)(this._Setting)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp)));
                typedTarget._Setting = tmp;
            }
            if ((this._Pose != null)) {
                global::PololuMaestro.Proxy.ChannelPose tmp0 = new global::PololuMaestro.Proxy.ChannelPose();
                ((Microsoft.Dss.Core.IDssSerializable)(this._Pose)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp0)));
                typedTarget._Pose = tmp0;
            }
        }
        
        /// <summary>
        ///Clones ChannelInfo
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::PololuMaestro.Proxy.ChannelInfo target0 = new global::PololuMaestro.Proxy.ChannelInfo();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current ChannelInfo to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            writer.Write(this._Index);
            if ((this._Setting == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._Setting)).Serialize(writer);
            }
            if ((this._Pose == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._Pose)).Serialize(writer);
            }
        }
        
        /// <summary>
        ///Deserializes ChannelInfo
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized ChannelInfo</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._Index = reader.ReadInt32();
            if ((reader.ReadByte() != 0)) {
                this._Setting = ((global::PololuMaestro.Proxy.ChannelSetting)(((Microsoft.Dss.Core.IDssSerializable)(new global::PololuMaestro.Proxy.ChannelSetting())).Deserialize(reader)));
            }
            if ((reader.ReadByte() != 0)) {
                this._Pose = ((global::PololuMaestro.Proxy.ChannelPose)(((Microsoft.Dss.Core.IDssSerializable)(new global::PololuMaestro.Proxy.ChannelPose())).Deserialize(reader)));
            }
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html", ElementName="ChannelSetting")]
    [global::System.ComponentModel.DescriptionAttribute("Servo settings")]
    public class ChannelSetting : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public ChannelSetting() {
        }
        
        private string _Name;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public string Name {
            get {
                return this._Name;
            }
            set {
                this._Name = value;
            }
        }
        
        private global::PololuMaestro.Proxy.ChannelMode _Mode;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::PololuMaestro.Proxy.ChannelMode Mode {
            get {
                return this._Mode;
            }
            set {
                this._Mode = value;
            }
        }
        
        private global::PololuMaestro.Proxy.HomeMode _HomeMode;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::PololuMaestro.Proxy.HomeMode HomeMode {
            get {
                return this._HomeMode;
            }
            set {
                this._HomeMode = value;
            }
        }
        
        private ushort _HomePosition;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public ushort HomePosition {
            get {
                return this._HomePosition;
            }
            set {
                this._HomePosition = value;
            }
        }
        
        private ushort _MinimumPosition;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public ushort MinimumPosition {
            get {
                return this._MinimumPosition;
            }
            set {
                this._MinimumPosition = value;
            }
        }
        
        private ushort _MaximumPosition;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public ushort MaximumPosition {
            get {
                return this._MaximumPosition;
            }
            set {
                this._MaximumPosition = value;
            }
        }
        
        private ushort _NeutralPosition;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public ushort NeutralPosition {
            get {
                return this._NeutralPosition;
            }
            set {
                this._NeutralPosition = value;
            }
        }
        
        private ushort _Range;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public ushort Range {
            get {
                return this._Range;
            }
            set {
                this._Range = value;
            }
        }
        
        private ushort _MaximumSpeed;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public ushort MaximumSpeed {
            get {
                return this._MaximumSpeed;
            }
            set {
                this._MaximumSpeed = value;
            }
        }
        
        private byte _MaximumAcceleration;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public byte MaximumAcceleration {
            get {
                return this._MaximumAcceleration;
            }
            set {
                this._MaximumAcceleration = value;
            }
        }
        
        private global::System.DateTime _Timestamp;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.DateTime Timestamp {
            get {
                return this._Timestamp;
            }
            set {
                this._Timestamp = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current ChannelSetting to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::PololuMaestro.Proxy.ChannelSetting typedTarget = ((global::PololuMaestro.Proxy.ChannelSetting)(target));
            typedTarget._Name = this._Name;
            typedTarget._Mode = this._Mode;
            typedTarget._HomeMode = this._HomeMode;
            typedTarget._HomePosition = this._HomePosition;
            typedTarget._MinimumPosition = this._MinimumPosition;
            typedTarget._MaximumPosition = this._MaximumPosition;
            typedTarget._NeutralPosition = this._NeutralPosition;
            typedTarget._Range = this._Range;
            typedTarget._MaximumSpeed = this._MaximumSpeed;
            typedTarget._MaximumAcceleration = this._MaximumAcceleration;
            typedTarget._Timestamp = this._Timestamp;
        }
        
        /// <summary>
        ///Clones ChannelSetting
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::PololuMaestro.Proxy.ChannelSetting target0 = new global::PololuMaestro.Proxy.ChannelSetting();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current ChannelSetting to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            if ((this._Name == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._Name);
            }
            writer.Write(((int)(this._Mode)));
            writer.Write(((int)(this._HomeMode)));
            writer.Write(this._HomePosition);
            writer.Write(this._MinimumPosition);
            writer.Write(this._MaximumPosition);
            writer.Write(this._NeutralPosition);
            writer.Write(this._Range);
            writer.Write(this._MaximumSpeed);
            writer.Write(this._MaximumAcceleration);
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeDateTime(this._Timestamp, writer);
        }
        
        /// <summary>
        ///Deserializes ChannelSetting
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized ChannelSetting</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            if ((reader.ReadByte() != 0)) {
                this._Name = reader.ReadString();
            }
            this._Mode = ((global::PololuMaestro.Proxy.ChannelMode)(reader.ReadInt32()));
            this._HomeMode = ((global::PololuMaestro.Proxy.HomeMode)(reader.ReadInt32()));
            this._HomePosition = reader.ReadUInt16();
            this._MinimumPosition = reader.ReadUInt16();
            this._MaximumPosition = reader.ReadUInt16();
            this._NeutralPosition = reader.ReadUInt16();
            this._Range = reader.ReadUInt16();
            this._MaximumSpeed = reader.ReadUInt16();
            this._MaximumAcceleration = reader.ReadByte();
            this._Timestamp = global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeDateTime(reader);
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html", ElementName="ChannelPose")]
    public class ChannelPose : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public ChannelPose() {
        }
        
        private ushort _Target;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public ushort Target {
            get {
                return this._Target;
            }
            set {
                this._Target = value;
            }
        }
        
        private ushort _Position;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public ushort Position {
            get {
                return this._Position;
            }
            set {
                this._Position = value;
            }
        }
        
        private byte _Acceleration;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public byte Acceleration {
            get {
                return this._Acceleration;
            }
            set {
                this._Acceleration = value;
            }
        }
        
        private ushort _Speed;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public ushort Speed {
            get {
                return this._Speed;
            }
            set {
                this._Speed = value;
            }
        }
        
        private global::System.DateTime _Timestamp;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.DateTime Timestamp {
            get {
                return this._Timestamp;
            }
            set {
                this._Timestamp = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current ChannelPose to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::PololuMaestro.Proxy.ChannelPose typedTarget = ((global::PololuMaestro.Proxy.ChannelPose)(target));
            typedTarget._Target = this._Target;
            typedTarget._Position = this._Position;
            typedTarget._Acceleration = this._Acceleration;
            typedTarget._Speed = this._Speed;
            typedTarget._Timestamp = this._Timestamp;
        }
        
        /// <summary>
        ///Clones ChannelPose
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::PololuMaestro.Proxy.ChannelPose target0 = new global::PololuMaestro.Proxy.ChannelPose();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current ChannelPose to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            writer.Write(this._Target);
            writer.Write(this._Position);
            writer.Write(this._Acceleration);
            writer.Write(this._Speed);
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeDateTime(this._Timestamp, writer);
        }
        
        /// <summary>
        ///Deserializes ChannelPose
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized ChannelPose</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._Target = reader.ReadUInt16();
            this._Position = reader.ReadUInt16();
            this._Acceleration = reader.ReadByte();
            this._Speed = reader.ReadUInt16();
            this._Timestamp = global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeDateTime(reader);
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html", ElementName="GetDeviceListResponseType")]
    public class GetDeviceListResponseType : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public GetDeviceListResponseType() {
        }
        
        private PololuMaestro.Proxy.DeviceListItem[] _Devices;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public PololuMaestro.Proxy.DeviceListItem[] Devices {
            get {
                return this._Devices;
            }
            set {
                this._Devices = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current GetDeviceListResponseType to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::PololuMaestro.Proxy.GetDeviceListResponseType typedTarget = ((global::PololuMaestro.Proxy.GetDeviceListResponseType)(target));
            if ((this._Devices != null)) {
                int count = this._Devices.Length;
                global::PololuMaestro.Proxy.DeviceListItem[] tmp = new global::PololuMaestro.Proxy.DeviceListItem[count];
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::PololuMaestro.Proxy.DeviceListItem tmp0 = default(global::PololuMaestro.Proxy.DeviceListItem);
                    if ((this._Devices[index] != null)) {
                        global::PololuMaestro.Proxy.DeviceListItem tmp1 = new global::PololuMaestro.Proxy.DeviceListItem();
                        ((Microsoft.Dss.Core.IDssSerializable)(this._Devices[index])).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp1)));
                        tmp0 = tmp1;
                    }
                    tmp[index] = tmp0;
                }
                typedTarget._Devices = tmp;
            }
        }
        
        /// <summary>
        ///Clones GetDeviceListResponseType
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::PololuMaestro.Proxy.GetDeviceListResponseType target0 = new global::PololuMaestro.Proxy.GetDeviceListResponseType();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current GetDeviceListResponseType to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            if ((this._Devices == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(1);
                writer.Write(this._Devices.Length);
                for (int indexDevices = 0; (indexDevices < this._Devices.Length); indexDevices = (indexDevices + 1)) {
                    if ((this._Devices[indexDevices] == null)) {
                        writer.Write(((byte)(0)));
                    }
                    else {
                        writer.Write(((byte)(1)));
                        ((Microsoft.Dss.Core.IDssSerializable)(this._Devices[indexDevices])).Serialize(writer);
                    }
                }
            }
        }
        
        /// <summary>
        ///Deserializes GetDeviceListResponseType
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized GetDeviceListResponseType</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            if ((reader.ReadByte() != 0)) {
                int tmp2 = reader.ReadInt32();
                int count0 = reader.ReadInt32();
                this._Devices = new global::PololuMaestro.Proxy.DeviceListItem[count0];
                for (int index0 = 0; (index0 < count0); index0 = (index0 + 1)) {
                    if ((reader.ReadByte() != 0)) {
                        this._Devices[index0] = ((global::PololuMaestro.Proxy.DeviceListItem)(((Microsoft.Dss.Core.IDssSerializable)(new global::PololuMaestro.Proxy.DeviceListItem())).Deserialize(reader)));
                    }
                }
            }
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html", ElementName="DeviceListItem")]
    public class DeviceListItem : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public DeviceListItem() {
        }
        
        private string _SerialNumber;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public string SerialNumber {
            get {
                return this._SerialNumber;
            }
            set {
                this._SerialNumber = value;
            }
        }
        
        private string _DisplayName;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public string DisplayName {
            get {
                return this._DisplayName;
            }
            set {
                this._DisplayName = value;
            }
        }
        
        private ushort _ProductId;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public ushort ProductId {
            get {
                return this._ProductId;
            }
            set {
                this._ProductId = value;
            }
        }
        
        private global::System.Guid _Guid;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.Guid Guid {
            get {
                return this._Guid;
            }
            set {
                this._Guid = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current DeviceListItem to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::PololuMaestro.Proxy.DeviceListItem typedTarget = ((global::PololuMaestro.Proxy.DeviceListItem)(target));
            typedTarget._SerialNumber = this._SerialNumber;
            typedTarget._DisplayName = this._DisplayName;
            typedTarget._ProductId = this._ProductId;
            typedTarget._Guid = this._Guid;
        }
        
        /// <summary>
        ///Clones DeviceListItem
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::PololuMaestro.Proxy.DeviceListItem target0 = new global::PololuMaestro.Proxy.DeviceListItem();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current DeviceListItem to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            if ((this._SerialNumber == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._SerialNumber);
            }
            if ((this._DisplayName == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._DisplayName);
            }
            writer.Write(this._ProductId);
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeAsXml(writer, this._Guid);
        }
        
        /// <summary>
        ///Deserializes DeviceListItem
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized DeviceListItem</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            if ((reader.ReadByte() != 0)) {
                this._SerialNumber = reader.ReadString();
            }
            if ((reader.ReadByte() != 0)) {
                this._DisplayName = reader.ReadString();
            }
            this._ProductId = reader.ReadUInt16();
            this._Guid = ((global::System.Guid)(global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeXml(reader, typeof(global::System.Guid))));
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html", ElementName="SetServoRequestType")]
    public class SetServoRequestType : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public SetServoRequestType() {
        }
        
        private int _ServoIndex;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public int ServoIndex {
            get {
                return this._ServoIndex;
            }
            set {
                this._ServoIndex = value;
            }
        }
        
        private global::System.Nullable<ushort> _Target;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.Nullable<ushort> Target {
            get {
                return this._Target;
            }
            set {
                this._Target = value;
            }
        }
        
        private global::System.Nullable<ushort> _Acceleration;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.Nullable<ushort> Acceleration {
            get {
                return this._Acceleration;
            }
            set {
                this._Acceleration = value;
            }
        }
        
        private global::System.Nullable<ushort> _Speed;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.Nullable<ushort> Speed {
            get {
                return this._Speed;
            }
            set {
                this._Speed = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current SetServoRequestType to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::PololuMaestro.Proxy.SetServoRequestType typedTarget = ((global::PololuMaestro.Proxy.SetServoRequestType)(target));
            typedTarget._ServoIndex = this._ServoIndex;
            typedTarget._Target = this._Target;
            typedTarget._Acceleration = this._Acceleration;
            typedTarget._Speed = this._Speed;
        }
        
        /// <summary>
        ///Clones SetServoRequestType
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::PololuMaestro.Proxy.SetServoRequestType target0 = new global::PololuMaestro.Proxy.SetServoRequestType();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current SetServoRequestType to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            writer.Write(this._ServoIndex);
            if ((this._Target.HasValue == false)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._Target.Value);
            }
            if ((this._Acceleration.HasValue == false)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._Acceleration.Value);
            }
            if ((this._Speed.HasValue == false)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._Speed.Value);
            }
        }
        
        /// <summary>
        ///Deserializes SetServoRequestType
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized SetServoRequestType</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._ServoIndex = reader.ReadInt32();
            if ((reader.ReadByte() != 0)) {
                this._Target = reader.ReadUInt16();
            }
            if ((reader.ReadByte() != 0)) {
                this._Acceleration = reader.ReadUInt16();
            }
            if ((reader.ReadByte() != 0)) {
                this._Speed = reader.ReadUInt16();
            }
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html", ElementName="ServoChangeRequestType")]
    public class ServoChangeRequestType : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public ServoChangeRequestType() {
        }
        
        private int _Index;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public int Index {
            get {
                return this._Index;
            }
            set {
                this._Index = value;
            }
        }
        
        private global::PololuMaestro.Proxy.ChannelPose _CurrentPose;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::PololuMaestro.Proxy.ChannelPose CurrentPose {
            get {
                return this._CurrentPose;
            }
            set {
                this._CurrentPose = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current ServoChangeRequestType to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::PololuMaestro.Proxy.ServoChangeRequestType typedTarget = ((global::PololuMaestro.Proxy.ServoChangeRequestType)(target));
            typedTarget._Index = this._Index;
            if ((this._CurrentPose != null)) {
                global::PololuMaestro.Proxy.ChannelPose tmp = new global::PololuMaestro.Proxy.ChannelPose();
                ((Microsoft.Dss.Core.IDssSerializable)(this._CurrentPose)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp)));
                typedTarget._CurrentPose = tmp;
            }
        }
        
        /// <summary>
        ///Clones ServoChangeRequestType
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::PololuMaestro.Proxy.ServoChangeRequestType target0 = new global::PololuMaestro.Proxy.ServoChangeRequestType();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current ServoChangeRequestType to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            writer.Write(this._Index);
            if ((this._CurrentPose == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._CurrentPose)).Serialize(writer);
            }
        }
        
        /// <summary>
        ///Deserializes ServoChangeRequestType
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized ServoChangeRequestType</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._Index = reader.ReadInt32();
            if ((reader.ReadByte() != 0)) {
                this._CurrentPose = ((global::PololuMaestro.Proxy.ChannelPose)(((Microsoft.Dss.Core.IDssSerializable)(new global::PololuMaestro.Proxy.ChannelPose())).Deserialize(reader)));
            }
            return this;
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Get : global::Microsoft.Dss.ServiceModel.Dssp.Get<global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType, global:: Microsoft.Ccr.Core.PortSet<global::PololuMaestro.Proxy.PololuMaestroState, global:: W3C.Soap.Fault>> {
        
        public Get() {
        }
        
        public Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body) {
        }
        
        public Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, global::Microsoft.Ccr.Core.PortSet<global::PololuMaestro.Proxy.PololuMaestroState, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Subscribe : global::Microsoft.Dss.ServiceModel.Dssp.Subscribe<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault>> {
        
        public Subscribe() {
        }
        
        public Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body) : 
                base(body) {
        }
        
        public Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Replace : global::Microsoft.Dss.ServiceModel.Dssp.Replace<global::PololuMaestro.Proxy.PololuMaestroState, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultReplaceResponseType, global:: W3C.Soap.Fault>> {
        
        public Replace() {
        }
        
        public Replace(global::PololuMaestro.Proxy.PololuMaestroState body) : 
                base(body) {
        }
        
        public Replace(global::PololuMaestro.Proxy.PololuMaestroState body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultReplaceResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class GetDeviceList : global::Microsoft.Dss.ServiceModel.Dssp.Get<global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType, global:: Microsoft.Ccr.Core.PortSet<global::PololuMaestro.Proxy.GetDeviceListResponseType, global:: W3C.Soap.Fault>> {
        
        public GetDeviceList() {
        }
        
        public GetDeviceList(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body) {
        }
        
        public GetDeviceList(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, global::Microsoft.Ccr.Core.PortSet<global::PololuMaestro.Proxy.GetDeviceListResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class SetChannel : global::Microsoft.Dss.ServiceModel.Dssp.Update<global::PololuMaestro.Proxy.SetServoRequestType, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault>> {
        
        public SetChannel() {
        }
        
        public SetChannel(global::PololuMaestro.Proxy.SetServoRequestType body) : 
                base(body) {
        }
        
        public SetChannel(global::PololuMaestro.Proxy.SetServoRequestType body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class ChannelChange : global::Microsoft.Dss.ServiceModel.Dssp.Update<global::PololuMaestro.Proxy.ServoChangeRequestType, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault>> {
        
        public ChannelChange() {
        }
        
        public ChannelChange(global::PololuMaestro.Proxy.ServoChangeRequestType body) : 
                base(body) {
        }
        
        public ChannelChange(global::PololuMaestro.Proxy.ServoChangeRequestType body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class PololuMaestroOperations : global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup, global:: Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop, global:: PololuMaestro.Proxy.Get, global:: Microsoft.Dss.Core.DsspHttp.HttpGet, global:: PololuMaestro.Proxy.Subscribe, global:: PololuMaestro.Proxy.Replace, global:: PololuMaestro.Proxy.GetDeviceList, global:: PololuMaestro.Proxy.SetChannel, global:: PololuMaestro.Proxy.ChannelChange> {
        
        public PololuMaestroOperations() {
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.LookupResponse, global::W3C.Soap.Fault> DsspDefaultLookup() {
            global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultLookup(out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.LookupResponse, global::W3C.Soap.Fault> DsspDefaultLookup(global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            }
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultLookup(global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body, out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            }
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType, global::W3C.Soap.Fault> DsspDefaultDrop() {
            global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultDrop(out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType, global::W3C.Soap.Fault> DsspDefaultDrop(global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            }
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultDrop(global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body, out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            }
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::PololuMaestro.Proxy.PololuMaestroState, global:: W3C.Soap.Fault> Get() {
            global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            global::PololuMaestro.Proxy.Get operation = new global::PololuMaestro.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Get(out global::PololuMaestro.Proxy.Get operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            operation = new global::PololuMaestro.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::PololuMaestro.Proxy.PololuMaestroState, global:: W3C.Soap.Fault> Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            }
            global::PololuMaestro.Proxy.Get operation = new global::PololuMaestro.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, out global::PololuMaestro.Proxy.Get operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            }
            operation = new global::PololuMaestro.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.Core.DsspHttp.HttpResponseType, global::W3C.Soap.Fault> HttpGet() {
            global::Microsoft.Dss.Core.DsspHttp.HttpGetRequestType body = new global::Microsoft.Dss.Core.DsspHttp.HttpGetRequestType();
            global::Microsoft.Dss.Core.DsspHttp.HttpGet operation = new global::Microsoft.Dss.Core.DsspHttp.HttpGet(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice HttpGet(out global::Microsoft.Dss.Core.DsspHttp.HttpGet operation) {
            global::Microsoft.Dss.Core.DsspHttp.HttpGetRequestType body = new global::Microsoft.Dss.Core.DsspHttp.HttpGetRequestType();
            operation = new global::Microsoft.Dss.Core.DsspHttp.HttpGet(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.Core.DsspHttp.HttpResponseType, global::W3C.Soap.Fault> HttpGet(global::Microsoft.Dss.Core.DsspHttp.HttpGetRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.Core.DsspHttp.HttpGetRequestType();
            }
            global::Microsoft.Dss.Core.DsspHttp.HttpGet operation = new global::Microsoft.Dss.Core.DsspHttp.HttpGet(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice HttpGet(global::Microsoft.Dss.Core.DsspHttp.HttpGetRequestType body, out global::Microsoft.Dss.Core.DsspHttp.HttpGet operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.Core.DsspHttp.HttpGetRequestType();
            }
            operation = new global::Microsoft.Dss.Core.DsspHttp.HttpGet(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault> Subscribe(global::Microsoft.Ccr.Core.IPort notificationPort, params System.Type[] types) {
            global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            global::PololuMaestro.Proxy.Subscribe operation = new global::PololuMaestro.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Subscribe(global::Microsoft.Ccr.Core.IPort notificationPort, out global::PololuMaestro.Proxy.Subscribe operation, params System.Type[] types) {
            global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            operation = new global::PololuMaestro.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault> Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body, global::Microsoft.Ccr.Core.IPort notificationPort, params System.Type[] types) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            }
            global::PololuMaestro.Proxy.Subscribe operation = new global::PololuMaestro.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body, global::Microsoft.Ccr.Core.IPort notificationPort, out global::PololuMaestro.Proxy.Subscribe operation, params System.Type[] types) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            }
            operation = new global::PololuMaestro.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultReplaceResponseType, global:: W3C.Soap.Fault> Replace() {
            global::PololuMaestro.Proxy.PololuMaestroState body = new global::PololuMaestro.Proxy.PololuMaestroState();
            global::PololuMaestro.Proxy.Replace operation = new global::PololuMaestro.Proxy.Replace(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Replace(out global::PololuMaestro.Proxy.Replace operation) {
            global::PololuMaestro.Proxy.PololuMaestroState body = new global::PololuMaestro.Proxy.PololuMaestroState();
            operation = new global::PololuMaestro.Proxy.Replace(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultReplaceResponseType, global:: W3C.Soap.Fault> Replace(global::PololuMaestro.Proxy.PololuMaestroState body) {
            if ((body == null)) {
                body = new global::PololuMaestro.Proxy.PololuMaestroState();
            }
            global::PololuMaestro.Proxy.Replace operation = new global::PololuMaestro.Proxy.Replace(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Replace(global::PololuMaestro.Proxy.PololuMaestroState body, out global::PololuMaestro.Proxy.Replace operation) {
            if ((body == null)) {
                body = new global::PololuMaestro.Proxy.PololuMaestroState();
            }
            operation = new global::PololuMaestro.Proxy.Replace(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::PololuMaestro.Proxy.GetDeviceListResponseType, global:: W3C.Soap.Fault> GetDeviceList() {
            global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            global::PololuMaestro.Proxy.GetDeviceList operation = new global::PololuMaestro.Proxy.GetDeviceList(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice GetDeviceList(out global::PololuMaestro.Proxy.GetDeviceList operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            operation = new global::PololuMaestro.Proxy.GetDeviceList(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::PololuMaestro.Proxy.GetDeviceListResponseType, global:: W3C.Soap.Fault> GetDeviceList(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            }
            global::PololuMaestro.Proxy.GetDeviceList operation = new global::PololuMaestro.Proxy.GetDeviceList(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice GetDeviceList(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, out global::PololuMaestro.Proxy.GetDeviceList operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            }
            operation = new global::PololuMaestro.Proxy.GetDeviceList(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> SetChannel() {
            global::PololuMaestro.Proxy.SetServoRequestType body = new global::PololuMaestro.Proxy.SetServoRequestType();
            global::PololuMaestro.Proxy.SetChannel operation = new global::PololuMaestro.Proxy.SetChannel(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice SetChannel(out global::PololuMaestro.Proxy.SetChannel operation) {
            global::PololuMaestro.Proxy.SetServoRequestType body = new global::PololuMaestro.Proxy.SetServoRequestType();
            operation = new global::PololuMaestro.Proxy.SetChannel(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> SetChannel(global::PololuMaestro.Proxy.SetServoRequestType body) {
            if ((body == null)) {
                body = new global::PololuMaestro.Proxy.SetServoRequestType();
            }
            global::PololuMaestro.Proxy.SetChannel operation = new global::PololuMaestro.Proxy.SetChannel(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice SetChannel(global::PololuMaestro.Proxy.SetServoRequestType body, out global::PololuMaestro.Proxy.SetChannel operation) {
            if ((body == null)) {
                body = new global::PololuMaestro.Proxy.SetServoRequestType();
            }
            operation = new global::PololuMaestro.Proxy.SetChannel(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> ChannelChange() {
            global::PololuMaestro.Proxy.ServoChangeRequestType body = new global::PololuMaestro.Proxy.ServoChangeRequestType();
            global::PololuMaestro.Proxy.ChannelChange operation = new global::PololuMaestro.Proxy.ChannelChange(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice ChannelChange(out global::PololuMaestro.Proxy.ChannelChange operation) {
            global::PololuMaestro.Proxy.ServoChangeRequestType body = new global::PololuMaestro.Proxy.ServoChangeRequestType();
            operation = new global::PololuMaestro.Proxy.ChannelChange(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> ChannelChange(global::PololuMaestro.Proxy.ServoChangeRequestType body) {
            if ((body == null)) {
                body = new global::PololuMaestro.Proxy.ServoChangeRequestType();
            }
            global::PololuMaestro.Proxy.ChannelChange operation = new global::PololuMaestro.Proxy.ChannelChange(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice ChannelChange(global::PololuMaestro.Proxy.ServoChangeRequestType body, out global::PololuMaestro.Proxy.ChannelChange operation) {
            if ((body == null)) {
                body = new global::PololuMaestro.Proxy.ServoChangeRequestType();
            }
            operation = new global::PololuMaestro.Proxy.ChannelChange(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html", ElementName="ChannelMode")]
    public enum ChannelMode : int {
        
        Servo = 0,
        
        ServoMultiplied = 1,
        
        Output = 2,
        
        Input = 3,
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2012/04/pololumaestro.html", ElementName="HomeMode")]
    public enum HomeMode : int {
        
        Off = 0,
        
        Ignore = 1,
        
        Goto = 2,
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    [global::System.ComponentModel.DescriptionAttribute("Pololu Maestro Servo Controller")]
    [global::System.ComponentModel.DisplayNameAttribute("PololuMaestroBoard")]
    public class Contract {
        
        public const string Identifier = "http://schemas.tempuri.org/2012/04/pololumaestro.html";
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="service">service path</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, string service, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.tempuri.org/2012/04/pololumaestro.html", service);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.tempuri.org/2012/04/pololumaestro.html", null);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
    }
    
    public class CombinedOperationsPort : global::Microsoft.Dss.Core.DssCombinedOperationsPort {
        
        public CombinedOperationsPort() {
            this.PololuMaestroOperations = new global::PololuMaestro.Proxy.PololuMaestroOperations();
            base.Initialize(new global::Microsoft.Dss.Core.DssOperationsPortMetadata(this.PololuMaestroOperations, "http://schemas.tempuri.org/2012/04/pololumaestro.html", "PololuMaestroOperations", ""));
        }
        
        public global::PololuMaestro.Proxy.PololuMaestroOperations PololuMaestroOperations;
    }
}
