//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("PololuMaestroTest")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("PololuMaestroTest")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="PololuMaestroDashboard.Y2012.M04, Version=1.0.0.0, Culture=neutral, PublicKeyToke" +
    "n=d6f1900a66fa3281")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformPololuMaestroDashboard {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::PololuMaestro.Dashboard.Proxy.PololuMaestroDashboardState), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_Dashboard_Proxy_PololuMaestroDashboardState_TO_PololuMaestro_Dashboard_PololuMaestroDashboardState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::PololuMaestro.Dashboard.PololuMaestroDashboardState), new global::Microsoft.Dss.Core.Attributes.Transform(PololuMaestro_Dashboard_PololuMaestroDashboardState_TO_PololuMaestro_Dashboard_Proxy_PololuMaestroDashboardState));
        }
        
        private static global::PololuMaestro.Dashboard.Proxy.PololuMaestroDashboardState _cachedInstance0 = new global::PololuMaestro.Dashboard.Proxy.PololuMaestroDashboardState();
        
        private static global::PololuMaestro.Dashboard.PololuMaestroDashboardState _cachedInstance = new global::PololuMaestro.Dashboard.PololuMaestroDashboardState();
        
        public static object PololuMaestro_Dashboard_Proxy_PololuMaestroDashboardState_TO_PololuMaestro_Dashboard_PololuMaestroDashboardState(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object PololuMaestro_Dashboard_PololuMaestroDashboardState_TO_PololuMaestro_Dashboard_Proxy_PololuMaestroDashboardState(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
