//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("RobotArm")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("RobotArm")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="RobotArm.Y2012.M04, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d6f1900a66fa" +
    "3281")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformRobotArm {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::RobotArm.Proxy.RobotArmState), new global::Microsoft.Dss.Core.Attributes.Transform(RobotArm_Proxy_RobotArmState_TO_RobotArm_RobotArmState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::RobotArm.RobotArmState), new global::Microsoft.Dss.Core.Attributes.Transform(RobotArm_RobotArmState_TO_RobotArm_Proxy_RobotArmState));
        }
        
        private static global::RobotArm.Proxy.RobotArmState _cachedInstance0 = new global::RobotArm.Proxy.RobotArmState();
        
        private static global::RobotArm.RobotArmState _cachedInstance = new global::RobotArm.RobotArmState();
        
        public static object RobotArm_Proxy_RobotArmState_TO_RobotArm_RobotArmState(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object RobotArm_RobotArmState_TO_RobotArm_Proxy_RobotArmState(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
